apiVersion: v1
kind: Service
metadata:
  name: mini-project-app-service
spec:
  # NodePort 타입으로 설정하여 외부에서 각 노드의 특정 포트로 접근할 수 있게 합니다.
  type: NodePort
  selector:
    # 이 서비스가 어떤 파드들을 바라볼지 선택합니다. (deployment의 라벨과 일치해야 함)
    app: mini-project-app
  ports:
    - protocol: TCP
      port: 80 # 서비스 자체의 포트
      targetPort: 8080 # 컨테이너가 열어놓은 포트 (deployment의 containerPort와 일치)
      # nodePort: 30007 # 특정 포트를 지정할 수도 있지만, 비워두면 쿠버네티스가 남는 포트를 자동 할당합니다.
